apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config
data:
  DB_DRIVER: org.postgresql.Driver
---
apiVersion: v1
kind: Secret
metadata:
  name: order-secret
type: Opaque
data:
  DB_URL: {{ printf "jdbc:postgresql://%s:%s/%s" (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase  | b64enc | quote }}
  DB_USER: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  DB_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
