apiVersion: v2
name: user-app
description: A Helm chart for Kubernetes

type: application

version: 0.1.0
appVersion: v1

dependencies:
  - name: postgresql
    version: 9.1.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - myapp-database