apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "notification-chart.fullname" . }}
  labels:
    {{- include "notification-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "notification-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "notification-chart.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          ports:
            - name: web
              containerPort: {{ .Values.app.port }}
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: DB_URL
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: DB_USER            
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: DB_PASSWORD
            - name: DB_DRIVER
              valueFrom:
                configMapKeyRef:
                  name: notification-config
                  key: DB_DRIVER