replicaCount: 1

nameOverride: notification

image:
  repository: mobikop/notification-service

app:
  port: 8080

service:
  type: NodePort
  port: 80

postgresql:
  enabled: true
  postgresqlUsername: myuser
  postgresqlPassword: passwd
  postgresqlDatabase: myapp
  service:
    port: "5432"
  persistence:
    size: 1Gi